name: Deno

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Check if it works with current deno version
    - cron: '42 2 * * 6' # weekly on Saturday 2:42 UTC

jobs:
  denofmt-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno lint
      - run: deno fmt --check

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno cache source/*.ts
      - run: deno check source/*.ts

  doc:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno cache source/mod.ts
      - run: deno doc --lint source/mod.ts

  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno cache source/mod.ts
      - run: deno publish --dry-run

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno cache source/*.ts
      - run: deno test --no-check --coverage=coverage/
      - run: deno coverage coverage/
