name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  denofmt-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno lint
      - run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno cache source/*.ts
      - run: deno task check
      - run: deno test

  backport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Backport
        run: npm run backport

      - run: npm pack
