name: Publish to JSR

on:
  push:
    branches:
      - main
    paths:
      - deno.json*

jobs:
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4

      - run: deno publish
