name: Node.js

on:
  push:
  pull_request:
  schedule:
    # Check if it works with current dependencies
    - cron: '42 2 * * 6' # weekly on Saturday 2:42 UTC

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
          - 14
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
      - run: npm pack
